[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/about"
  to = "/mission"
  status = 301

[[redirects]]
  from = "/lenders-digest"
  to = "/insights"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@sentry/netlify-build-plugin"
  [plugins.inputs]
    setCommits = false



